Update prompt and delete unnecessary stacks
aws-ia/ecs-blueprints pull request #241
Opened 2024-10-21 23:52 UTC by raphael-shin

## Description
- remove DDB stack
- remove Lambda funtion
- update prompt

## Motivation and Context

## How Has This Been Tested?
- [ ] I have tested and validated these changes using one or more of the provided `examples/*` projects
- [ ] I have executed `pre-commit run -a` on my pull request

2024-10-21 23:54 UTC, joozero requested changes

2024-10-21 23:54 UTC, joozero commented on cdk/examples/other_stack/bedrock_agent_stack.py
Do we still need DDB?

2024-10-21 23:58 UTC, raphael-shin commented on cdk/examples/other_stack/bedrock_agent_stack.py
Oops. I missed.

2024-10-22 00:02 UTC, joozero approved these changes

2024-10-22 00:29 UTC, merged